title: Piotr Romanowski
email: piotr.michal.romanowski@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Programowanie / Muzyka / DIY
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MrBananovitch
github_username: bananovitch

plugins:
  - jekyll-feed

permalink:
  /:categories/:title/
  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: "" #default layout for everything
    values:
      layout: "default"
  - scope:
      path: "" # post layout
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
